#include <Arduino.h>
const char* mppindex __attribute__((section(".irom.text"))) =
"<html>\n"
"<head>\n"
"<title>MppDevices</title>\n"
"<style>\n"
"body {font-size: 12px;line-height: 1.2;}\n"
".loading {border: 5px solid #f3f3f3;border-radius: 50%;border-top: 5px solid #3498db;width: 20px;height: 20px;animation: spin 2s linear infinite;}\n"
"@keyframes spin {0% {transform: rotate(0deg);}100% {transform: rotate(360deg);}}\n"
"</style>\n"
"</head>\n"
"<body onload='loadState()'>\n"
"<script>\n"
"function loadState() {\n"
"var xProps = new XMLHttpRequest();\n"
"xProps.onreadystatechange = function() {\n"
"if (this.readyState == 4) {\n"
"if (this.status == 200) {\n"
"var jsonProps = JSON.parse(xProps.responseText);\n"
"var oldTable = document.getElementById('props'), newTable = oldTable.cloneNode(true);\n"
"var oldChoices = document.getElementById('dprops'), newChoices = oldChoices.cloneNode(true);\n"
"for ( var key in jsonProps) {\n"
"var tr = document.createElement('tr');\n"
"var td = document.createElement('td');\n"
"td.appendChild(document.createTextNode(key));\n"
"tr.appendChild(td);\n"
"td = document.createElement('td');\n"
"var val = jsonProps[key];\n"
"if (val == null) val = '';\n"
"td.appendChild(document.createTextNode(val));\n"
"tr.appendChild(td);\n"
"newTable.appendChild(tr);\n"
"var ov = document.createElement('option');\n"
"ov.setAttribute('value', key);\n"
"ov.appendChild(document.createTextNode(key));\n"
"newChoices.appendChild(ov);\n"
"}\n"
"oldTable.parentNode.replaceChild(newTable, oldTable);\n"
"oldChoices.parentNode.replaceChild(newChoices, oldChoices);\n"
"} else {\n"
"alert('Error loading properties ' + this.status);\n"
"}\n"
"document.getElementById('propsLoading').style.display = 'none';\n"
"}\n"
"};\n"
"xProps.open('GET', 'props', true);\n"
"xProps.send();\n"
"var xVersion = new XMLHttpRequest();\n"
"xVersion.onreadystatechange = function() {\n"
"if (this.readyState == 4) {\n"
"if (this.status == 200) {\n"
"document.getElementById('dVersion').innerHTML = xVersion.responseText;\n"
"} else {\n"
"document.getElementById('dVersion').innerHTML = this.status;\n"
"}\n"
"}\n"
"};\n"
"xVersion.open('GET', 'version', true);\n"
"xVersion.send();\n"
"}\n"
"</script>\n"
"<h1>MppDevice Configuration (ESP32)</h1>\n"
"<h4>Properties</h4>\n"
"<div class='loading' id='propsLoading'></div>\n"
"<table id='props' border='1'>\n"
"</table>\n"
"<br>\n"
"<form action='downloadprops' method='get'>\n"
"<input type='submit' value='Download Properties'/>\n"
"</form>\n"
"<form action='uploadprops' method='post' enctype='multipart/form-data'>\n"
"<input type='file' name='fileToUpload' id='fileToUpload'>\n"
"<input type='submit' value='Restore Properties' name='submit'>\n"
"</form>\n"
"Modify Property\n"
"<form action='setprops' method='get'>\n"
"<select name='keyselect' id='dprops'></select>\n"
"or\n"
"<input type='text' name='keyname' value='' maxlength='100' width='50px' placeholder='property' />\n"
"<br>set to<br>\n"
"<input type='text' name='value' value='' maxlength='100' width='100px' />\n"
"&nbsp;\n"
"<input type='submit' value='Set'/>&nbsp;(empty to remove)\n"
"</form>\n"
"<form action='reset' method='get'>\n"
"<input type='submit' value='Clear Properties'/>\n"
"</form>\n"
"<h4>Update Firmware</h4>\n"
"<form action='upload' method='post' enctype='multipart/form-data'>\n"
"<input type='file' name='fileToUpload' id='fileToUpload'>\n"
"<input type='submit' value='Upload Firmware' name='submit'>\n"
"</form>\n"
"<h4>Restart</h4>\n"
"<form action='restart' method='get'>\n"
"<input type='submit' value='Restart Device'/>\n"
"</form>\n"
"<h4>Version</h4>\n"
"<p id='dVersion'></p>\n"
"</body>\n"
"</html>\n";
/*
const char* mppindex __attribute__((section(".irom.text"))) =
"<html>\n"
"<head>\n"
"<title>MppDevices</title>\n"
"<style>\n"
".loading {\n"
"    border: 5px solid #f3f3f3;\n"
"    border-radius: 50%;\n"
"    border-top: 5px solid #3498db;\n"
"    width: 20px;\n"
"    height: 20px;\n"
"    animation: spin 2s linear infinite;\n"
"}\n"
"@keyframes spin {\n"
"    0% { transform: rotate(0deg); }\n"
"    100% { transform: rotate(360deg); }\n"
"}\n"
"</style>\n"
"</head>\n"
"<body onload='loadState()'>\n"
"<script>\n"
"function loadState() {\n"
"    var xProps = new XMLHttpRequest();\n"
"    xProps.onreadystatechange = function() {\n"
"        if (this.readyState == 4) {\n"
"            if (this.status == 200) {\n"
"                var jsonProps = JSON.parse(xProps.responseText);\n"
"                var oldTable = document.getElementById('props'), newTable = oldTable.cloneNode(true);\n"
"                var oldChoices = document.getElementById('dprops'), newChoices = oldChoices.cloneNode(true);\n"
"                for ( var key in jsonProps) {\n"
"                    var tr = document.createElement('tr');\n"
"                    var td = document.createElement('td');\n"
"                    td.appendChild(document.createTextNode(key));\n"
"                    tr.appendChild(td);\n"
"                    td = document.createElement('td');\n"
"                    var val = jsonProps[key];\n"
"                    if (val == null) val = '';\n"
"                    td.appendChild(document.createTextNode(val));\n"
"                    tr.appendChild(td);\n"
"                    newTable.appendChild(tr);\n"
"                    var ov = document.createElement('option');\n"
"                    ov.setAttribute('value', key);\n"
"                    ov.appendChild(document.createTextNode(key));\n"
"                    newChoices.appendChild(ov);\n"
"                }\n"
"                oldTable.parentNode.replaceChild(newTable, oldTable);\n"
"                oldChoices.parentNode.replaceChild(newChoices, oldChoices);\n"
"            } else {\n"
"                alert('Error loading properties ' + this.status);\n"
"            }\n"
"            document.getElementById('propsLoading').style.display = 'none';\n"
"        }\n"
"    };\n"
"    xProps.open('GET', 'props', true);\n"
"    xProps.send();\n"
"    var xVersion = new XMLHttpRequest();\n"
"    xVersion.onreadystatechange = function() {\n"
"        if (this.readyState == 4) {\n"
"            if (this.status == 200) {\n"
"                document.getElementById('dVersion').innerHTML = xVersion.responseText;\n"
"            } else {\n"
"                document.getElementById('dVersion').innerHTML = this.status;\n"
"            }\n"
"        }\n"
"    };\n"
"    xVersion.open('GET', 'version', true);\n"
"    xVersion.send();\n"
"}\n"
"</script>\n"
"<h1>MppDevice Configuration (ESP32)</h1>\n"
"<h4>Properties</h4>\n"
"<div class='loading' id='propsLoading'></div>\n"
"<table id='props' border='1'>\n"
"</table>\n"
"<br>\n"
"<form action='downloadprops' method='get'>\n"
"    <input type='submit' value='Download Properties'/>\n"
"</form>\n"
"<form action='uploadprops' method='post' enctype='multipart/form-data'>\n"
"    <input type='file' name='fileToUpload' id='fileToUpload'>\n"
"    <input type='submit' value='Restore Properties' name='submit'>\n"
"</form>\n"
"Modify Property\n"
"<form action='setprops' method='get'>\n"
"    <select name='keyselect' id='dprops'></select>\n"
"    or\n"
"    <input type='text' name='keyname' value='' maxlength='100' width='50px' placeholder='property' />\n"
"    <br>set to<br>\n"
"    <input type='text' name='value' value='' maxlength='100' width='100px' />\n"
"    &nbsp;\n"
"    <input type='submit' value='Set'/>&nbsp;(empty to remove)\n"
"</form>\n"
"<form action='reset' method='get'>\n"
"    <input type='submit' value='Clear Properties'/>\n"
"</form>\n"
"<h4>Update Firmware</h4>\n"
"<form action='upload' method='post' enctype='multipart/form-data'>\n"
"    <input type='file' name='fileToUpload' id='fileToUpload'>\n"
"    <input type='submit' value='Upload Firmware' name='submit'>\n"
"</form>\n"
"<h4>Restart</h4>\n"
"<form action='restart' method='get'>\n"
"    <input type='submit' value='Restart Device'/>\n"
"</form>\n"
"<h4>Version</h4>\n"
"<p id='dVersion'></p>\n"
"</body>\n"
"</html>\n";*/
//"<html>\n<head>\n<title>MppDevices</title>\n<style>\n.loading {\nborder: 5px solid #f3f3f3;\nborder-radius: 50%;\nborder-top: 5px solid #3498db;\nwidth: 20px;\nheight: 20px;\nanimation: spin 2s linear infinite;\n}\n@keyframes spin {\n0% { transform: rotate(0deg); }\n100% { transform: rotate(360deg); }\n}\n</style>\n</head>\n<body onload='loadState()'>\n<script>\nfunction loadState() {\ndocument.getElementById('ssidsLoading').style.display = 'none';\nvar xProps = new XMLHttpRequest();\nxProps.onreadystatechange = function() {\nif (this.readyState == 4) {\nif (this.status == 200) {\nvar jsonProps = JSON.parse(xProps.responseText);\nvar oldTable = document.getElementById('props'), newTable = oldTable\n.cloneNode(true);\nvar oldChoices = document.getElementById('dprops'), newChoices = oldChoices\n.cloneNode(true)\nfor ( var key in jsonProps) {\nvar tr = document.createElement('tr');\nvar td = document.createElement('td');\ntd.appendChild(document.createTextNode(key));\ntr.appendChild(td);\n"
//"td = document.createElement('td');var val = jsonProps[key];\nif (val == null) val = '';\ntd.appendChild(document\n.createTextNode(val));\ntr.appendChild(td);\nnewTable.appendChild(tr);\nvar ov = document.createElement('option');\nov.setAttribute('value', key);\nov.appendChild(document.createTextNode(key));\nnewChoices.appendChild(ov);\n}\noldTable.parentNode.replaceChild(newTable, oldTable);\noldChoices.parentNode.replaceChild(newChoices,oldChoices);\n} else {\nalert('Error loading properties ' + this.status);\n}\ndocument.getElementById('propsLoading').style.display = 'none';\n}\n};\nxProps.open('GET', 'props', true);\nxProps.send();\nvar xVersion = new XMLHttpRequest();\nxVersion.onreadystatechange = function() {\nif (this.readyState == 4) {\nif (this.status == 200) {\ndocument.getElementById('dVersion').innerHTML = xVersion.responseText;\n} else {\ndocument.getElementById('dVersion').innerHTML = this.status;\n}\n}\n};\nxVersion.open('GET', 'version', true);\nxVersion.send();\n}\nfunction scanWifi() {\n"
//"document.getElementById('ssidsLoading').style.display = 'block';document.getElementById('ssidButton').style.display = 'none';\nvar xSsids = new XMLHttpRequest();\nxSsids.onreadystatechange = function() {\nif (this.readyState == 4) {\nif (this.status == 200) {\nvar jsonSsids = JSON.parse(xSsids.responseText);\nvar oldChoices = document.getElementById('dSsids'), newChoices = oldChoices\n.cloneNode(false)\nfor (i in jsonSsids) {\n// '<option value=''..k..''>'..k..'</option>'\nvar ov = document.createElement('option');\nvar ssid = jsonSsids[i].ssid;\nov.setAttribute('value', ssid);\nov.appendChild(document.createTextNode(ssid\n+ ' ch=' + jsonSsids[i].channel + ' rssi='\n+ jsonSsids[i].rssi));\nnewChoices.appendChild(ov);\n}\noldChoices.parentNode.replaceChild(newChoices,\noldChoices);\n} else {\nalert('Error loading ssids ' + this.status);\n}\ndocument.getElementById('ssidsLoading').style.display = 'none';\ndocument.getElementById('ssidButton').style.display = 'block';\n}\n};\nxSsids.open('GET', 'scan', true);\n"
//"xSsids.send();}\n</script>\n<h1>MppDevice Configuration (ESP32)</h1>\n<h4>SSID</h4>\n<button onclick='scanWifi()' id='ssidButton'>Scan</button>\n<div class='loading' id='ssidsLoading'></div>\n<p>\n<form action='setwifi' method='get'>\n<input type='text' name='ssid' value='' maxlength='100' width='100px'\nplaceholder='ssid' /> &nbsp;or&nbsp; <select name='dssid'\nid='dSsids'></select>\n<h4>Password</h4>\n<input type='text' name='password' value='' maxlength='100'\nwidth='100px' placeholder='empty for open AP' />\n<p>\n<input type='submit' value='Set Wifi' />\n</form>\n<h4>Properties</h4>\n<div class='loading' id='propsLoading'></div>\n<table id='props' border='1'>\n</table>\n<br>\n<form action='downloadprops' method='get'>\n<input type='submit' value='Download Properties'/>\n</form>\n<form action='uploadprops' method='post' enctype='multipart/form-data'>\n<input type='file' name='fileToUpload' id='fileToUpload'>\n<input type='submit' value='Restore Properties' name='submit'>\n</form>\nModify Property\n"
//"<form action='setprops' method='get'><select name='keyselect' id='dprops'></select>\nor\n<input type='text' name='keyname' value='' maxlength='100' width='50px' placeholder='property' />\n<br>set to<br>\n<input type='text' name='value' value='' maxlength='100' width='100px' />\n&nbsp;\n<input type='submit' value='Set'/>&nbsp;(empty to remove)\n</form>\n<form action='reset' method='get'>\n<input type='submit' value='Clear Properties'/>\n</form>\n<h4>Update Firmware</h4>\n<form action='upload' method='post' enctype='multipart/form-data'>\n<input type='file' name='fileToUpload' id='fileToUpload'>\n<input type='submit' value='Upload Firmware' name='submit'>\n</form>\n<h4>Restart</h4>\n<form action='restart' method='get'>\n<input type='submit' value='Restart Device'/>\n</form>\n<h4>Version</h4>\n<p id='dVersion'></p>\n</body>\n</html>\n"
//;
